  
# mkdir ~/jenkins
version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    # restart: always
    privileged: true
    user: root
    # hostname: 'jenkins.example.com'
    ports:
      - 8080:8080
      - 50000:50000
      - 4433:443
    container_name: jenkins
    env_file: .env
    volumes:
      - /home/vagrant/docker-data/jenkins/var:/var/jenkins_home
      
#      - ~/jenkins/usr:/usr
#    command: sh -c "apt-get update && apt-get install -y maven && apt install -y openjdk-8-jdk"

# apt-get update && apt-get install -y maven
# apt install openjdk-8-jdk
#
