# sudo docker run --detach \
#   --hostname gitlab.example.com \
#   --publish 443:443 --publish 80:80 --publish 22:22 \
#   --name gitlab \
#   --restart always \
#   --volume $GITLAB_HOME/config:/etc/gitlab \
#   --volume $GITLAB_HOME/logs:/var/log/gitlab \
#   --volume $GITLAB_HOME/data:/var/opt/gitlab \
#   gitlab/gitlab-ee:latest

version: "3"  
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    hostname: 192.168.50.10
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    #restart: always
    env_file: .env
    volumes:
      - /home/vagrant/docker-data/gitlab/config:/etc/gitlab
      - /home/vagrant/docker-data/gitlab/data/logs:/var/log/gitlab
      - /home/vagrant/docker-data/gitlab/data/data:/var/opt/gitlab
