version: "3"
services:
    wireguard:
        image: ghcr.io/linuxserver/wireguard
        container_name: wireguard
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        env_file: .env    
        # environment: 
        #     - PUID=1000
        #     - PGID=1000
        #     - TZ=Europe/London
        #     - PEERS=1
        volumes:
            - /home/vagrant/docker-data/wireguard/config:/config
            - /home/vagrant/docker-data/wireguard/lib/modules:/lib/modules
        ports:
            - 51820:51820/udp
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped